# Generated by Django 6.1.1 on 2026-09-28 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('WITHDRAWN', 'Withdrawn'), ('DISQUALIFIED', 'Disqualified'), ('DUPLICATE', 'Duplicate')], default='DRAFT', max_length=20)),
                ('first_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('disposition_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='submissions.project')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='events.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='teams.team')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(max_length=500)),
                ('description_md', models.TextField(blank=True, max_length=100000)),
                ('repo_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('demo_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('roster_snapshot', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('USER', 'User'), ('FIXTURE_IMPORT', 'Fixture Import'), ('PORTABLE_IMPORT', 'Portable Import')], default='USER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='submissions.project')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_revisions', to='events.track')),
            ],
            options={
                'db_table': 'project_revisions',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='draft_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.projectrevision'),
        ),
        migrations.AddField(
            model_name='project',
            name='submitted_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.projectrevision'),
        ),
        migrations.AddIndex(
            model_name='projectrevision',
            index=models.Index(fields=['track', 'project'], name='idx_proj_rev_track'),
        ),
        migrations.AddConstraint(
            model_name='projectrevision',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='unique_project_revision_number'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['event', 'state', 'last_submitted_at', 'id'], name='idx_proj_gallery'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['DRAFT', 'SUBMITTED'])), fields=('event', 'team'), name='unique_active_project_per_team'),
        ),
    ]
