# Generated by Django 6.1.1 on 2026-09-28 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_attachments', to='media_assets.asset')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_assets', to='submissions.projectrevision')),
            ],
            options={
                'db_table': 'revision_assets',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('revision', 'asset'), name='unique_revision_asset')],
            },
        ),
    ]
