# Generated by Django 6.1.1 on 2026-09-29 06:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_eventinvitation'),
        ('results', '0002_communityresultrow'),
        ('submissions', '0002_revisionasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='award_decisions', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='award_decisions', to='events.prize')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='award_decisions', to='submissions.project')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='award_decisions', to='results.publication')),
            ],
            options={
                'db_table': 'award_decisions',
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('JUDGE', 'Judge'), ('WINNER', 'Winner')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('body_text', models.TextField(blank=True, max_length=2000)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('logo_asset_key', models.CharField(blank=True, max_length=512, null=True)),
                ('layout_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificate_templates', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='events.event')),
            ],
            options={
                'db_table': 'certificate_templates',
                'ordering': ['kind', '-version'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('JUDGE', 'Judge'), ('WINNER', 'Winner')], max_length=20)),
                ('template_version', models.PositiveIntegerField(blank=True, null=True)),
                ('eligibility_snapshot', models.JSONField(default=dict)),
                ('display_name_snapshot', models.CharField(max_length=200)),
                ('payload_bytes', models.BinaryField(help_text='Exact canonical JSON bytes that were signed.')),
                ('signature_bytes', models.BinaryField()),
                ('pdf_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('award_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='credentials.awarddecision')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_credentials', to='events.event')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='results.publication')),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='credentials.certificatetemplate')),
            ],
            options={
                'db_table': 'issued_credentials',
            },
        ),
        migrations.CreateModel(
            name='CredentialStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('REVOKED', 'Revoked'), ('SUPERSEDED', 'Superseded')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_status_events', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='credentials.issuedcredential')),
                ('replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces_events', to='credentials.issuedcredential')),
            ],
            options={
                'db_table': 'credential_status_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicRecordConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_public_fields', models.JSONField(default=list, help_text="List of fields allowed for public display, e.g. ['display_name', 'contribution_summary']")),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_consents', to='events.event')),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public_record_consents',
            },
        ),
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.CharField(max_length=64, unique=True)),
                ('issuer_id', models.CharField(max_length=128)),
                ('algorithm', models.CharField(default='ED25519', max_length=20)),
                ('public_key_bytes', models.BinaryField()),
                ('private_key_ref', models.CharField(blank=True, help_text='Reference to private key in secure store. Null for imported public-only keys.', max_length=512, null=True)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('COMPROMISED', 'Compromised')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'signing_keys',
                'indexes': [models.Index(fields=['state', 'created_at'], name='idx_signing_key_state')],
            },
        ),
        migrations.AddField(
            model_name='issuedcredential',
            name='signing_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='credentials.signingkey'),
        ),
        migrations.AddConstraint(
            model_name='awarddecision',
            constraint=models.UniqueConstraint(fields=('publication', 'prize', 'project'), name='unique_award_pub_prize_project'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.UniqueConstraint(fields=('event', 'kind', 'version'), name='unique_cert_template_event_kind_version'),
        ),
        migrations.AddIndex(
            model_name='credentialstatusevent',
            index=models.Index(fields=['credential', 'created_at'], name='idx_cred_status_cred_time'),
        ),
        migrations.AddConstraint(
            model_name='publicrecordconsent',
            constraint=models.UniqueConstraint(fields=('event', 'subject_user'), name='unique_public_consent_event_user'),
        ),
        migrations.AddIndex(
            model_name='issuedcredential',
            index=models.Index(fields=['event', 'subject_user', 'kind'], name='idx_cred_event_subject_kind'),
        ),
        migrations.AddConstraint(
            model_name='issuedcredential',
            constraint=models.UniqueConstraint(fields=('event', 'subject_user', 'kind', 'template_version', 'publication'), name='unique_credential_issuance_key'),
        ),
    ]
