# Generated by Django 6.1.1 on 2026-09-28 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=80)),
                ('format_version', models.CharField(default='1.0', max_length=20)),
                ('file_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('VALIDATED', 'Validated'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], max_length=20)),
                ('report_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batches',
            },
        ),
        migrations.CreateModel(
            name='ExternalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=40)),
                ('external_id', models.CharField(max_length=100)),
                ('internal_id', models.UUIDField()),
                ('original_payload_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='imports.importbatch')),
            ],
            options={
                'db_table': 'external_records',
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('namespace', 'file_sha256'), name='unique_import_batch_file'),
        ),
        migrations.AddConstraint(
            model_name='externalrecord',
            constraint=models.UniqueConstraint(fields=('namespace', 'entity_type', 'external_id'), name='unique_external_record'),
        ),
    ]
