# Generated by Django 6.1.1 on 2026-09-29 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortableImportPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('archive_sha256', models.CharField(max_length=64)),
                ('source_instance_id', models.CharField(max_length=120)),
                ('format_version', models.CharField(default='1', max_length=20)),
                ('preview_json', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('target_event_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portable_import_plans',
                'indexes': [models.Index(fields=['expires_at', 'applied_at'], name='idx_import_plan_cleanup'), models.Index(fields=['source_instance_id', 'archive_sha256'], name='idx_import_plan_source_hash')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('applied_at__isnull', False)), fields=('source_instance_id', 'archive_sha256'), name='unique_applied_portable_import_plan')],
            },
        ),
    ]
