# Generated by Django 6.1.1 on 2026-09-28 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_kind', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('IMPORT', 'Import')], default='USER', max_length=20)),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='events.event')),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at', 'id'], name='idx_audit_timeline')],
            },
        ),
    ]
