# Generated by Django 6.1.1 on 2026-09-28 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_eventinvitation'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('EVENT_IMAGE', 'Event Image'), ('PROJECT_IMAGE', 'Project Image'), ('PROJECT_FILE', 'Project File')], max_length=20)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('STAGED', 'Staged'), ('READY', 'Ready'), ('REJECTED', 'Rejected')], default='STAGED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='events.event')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='submissions.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets',
                'indexes': [models.Index(fields=['state', 'created_at'], name='idx_asset_staged')],
            },
        ),
    ]
