# Generated by Django 6.1.1 on 2026-09-28 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_eventinvitation'),
        ('submissions', '0002_revisionasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_email_encrypted', models.TextField(blank=True)),
                ('email_digest', models.CharField(max_length=64)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_challenges', to='events.event')),
            ],
            options={
                'db_table': 'email_challenges',
            },
        ),
        migrations.CreateModel(
            name='VotingLinkGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('recipient_label_encrypted', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_voting_link_grants', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_link_grants', to='events.event')),
            ],
            options={
                'db_table': 'voting_link_grants',
            },
        ),
        migrations.CreateModel(
            name='VoterIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('USER', 'User'), ('EMAIL', 'Email'), ('LINK', 'Link')], max_length=10)),
                ('email_digest', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_identities', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voter_identities', to=settings.AUTH_USER_MODEL)),
                ('link_grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voter_identities', to='voting.votinglinkgrant')),
            ],
            options={
                'db_table': 'voter_identities',
            },
        ),
        migrations.CreateModel(
            name='VotingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('AUTHENTICATED', 'Authenticated'), ('INVITE_LINK', 'Invite Link'), ('EMAIL_VERIFIED', 'Email Verified')], default='AUTHENTICATED', max_length=20)),
                ('minimum_account_age_seconds', models.PositiveIntegerField(default=0)),
                ('comments_enabled', models.BooleanField(default=False)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_policy', to='events.event')),
            ],
            options={
                'db_table': 'voting_policies',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('VOID', 'Void')], default='ACTIVE', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='submissions.project')),
                ('voter_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.voteridentity')),
            ],
            options={
                'db_table': 'votes',
                'constraints': [models.UniqueConstraint(fields=('event', 'project', 'voter_identity'), name='unique_vote_event_project_identity')],
            },
        ),
        migrations.CreateModel(
            name='BallotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordering_seed', models.CharField(max_length=128)),
                ('eligible_project_ids', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_sessions', to='events.event')),
                ('voter_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_sessions', to='voting.voteridentity')),
            ],
            options={
                'db_table': 'ballot_sessions',
                'constraints': [models.UniqueConstraint(fields=('event', 'voter_identity'), name='unique_ballot_session_event_identity')],
            },
        ),
        migrations.AddConstraint(
            model_name='voteridentity',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='unique_voter_identity_user'),
        ),
        migrations.AddConstraint(
            model_name='voteridentity',
            constraint=models.UniqueConstraint(condition=models.Q(('email_digest__isnull', False)), fields=('event', 'email_digest'), name='unique_voter_identity_email'),
        ),
        migrations.AddConstraint(
            model_name='voteridentity',
            constraint=models.UniqueConstraint(condition=models.Q(('link_grant__isnull', False)), fields=('event', 'link_grant'), name='unique_voter_identity_link'),
        ),
        migrations.AddConstraint(
            model_name='voteridentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'USER'), ('user__isnull', False), ('email_digest__isnull', True), ('link_grant__isnull', True)), models.Q(('kind', 'EMAIL'), ('email_digest__isnull', False), ('user__isnull', True), ('link_grant__isnull', True)), models.Q(('kind', 'LINK'), ('link_grant__isnull', False), ('user__isnull', True), ('email_digest__isnull', True)), _connector='OR'), name='check_voter_identity_principal'),
        ),
    ]
