# Generated by Django 6.1.1 on 2026-09-28 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventinvitation'),
        ('submissions', '0002_revisionasset'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('RAPID_ACCOUNT_VOTES', 'Rapid Account Votes'), ('EXCESSIVE_FAILED_TOKENS', 'Excessive Failed Tokens'), ('REPEATED_CONTENT', 'Repeated Content'), ('REPEATED_REPO_SUBMISSION', 'Repeated Repository Submission'), ('VOTING_BURST', 'Voting Burst'), ('SUSPICIOUS_NETWORK', 'Suspicious Network Activity'), ('OTHER', 'Other')], default='OTHER', max_length=64)),
                ('subject_id', models.CharField(blank=True, max_length=128, null=True)),
                ('network_key', models.CharField(blank=True, max_length=64, null=True)),
                ('details_json', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_signals', to='events.event')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_abuse_signals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'abuse_signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('COMMENT', 'Comment'), ('VOTE', 'Vote'), ('VOTER_IDENTITY', 'Voter Identity'), ('ABUSE_SIGNAL', 'Abuse Signal'), ('PROJECT', 'Project')], max_length=32)),
                ('target_id', models.UUIDField()),
                ('reason_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('HIDE_COMMENT', 'Hide Comment'), ('RESTORE_COMMENT', 'Restore Comment'), ('SUSPEND_IDENTITY', 'Suspend Voter Identity'), ('VOID_VOTES', 'Void Votes'), ('DISMISS_SIGNAL', 'Dismiss Signal'), ('NO_ACTION', 'No Action')], max_length=64)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_cases', to='events.event')),
                ('reporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_moderation_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, max_length=5000)),
                ('state', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden'), ('DELETED', 'Deleted')], default='VISIBLE', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='submissions.project')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['VISIBLE', 'HIDDEN', 'DELETED'])), name='check_comment_state')],
            },
        ),
    ]
