# Generated by Django 6.1.1 on 2026-09-28 04:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('description_md', models.TextField(blank=True, max_length=100000)),
                ('rules_md', models.TextField(blank=True, max_length=100000)),
                ('cover_asset_id', models.UUIDField(blank=True, null=True)),
                ('timezone', models.CharField(default='Australia/Melbourne', max_length=64)),
                ('lifecycle', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('registration_opens_at', models.DateTimeField()),
                ('registration_closes_at', models.DateTimeField()),
                ('submissions_opens_at', models.DateTimeField()),
                ('submissions_closes_at', models.DateTimeField()),
                ('judging_opens_at', models.DateTimeField()),
                ('judging_closes_at', models.DateTimeField()),
                ('voting_opens_at', models.DateTimeField(blank=True, null=True)),
                ('voting_closes_at', models.DateTimeField(blank=True, null=True)),
                ('min_team_size', models.PositiveIntegerField(default=1)),
                ('max_team_size', models.PositiveIntegerField(default=4)),
                ('required_reviews', models.PositiveIntegerField(default=3)),
                ('ranking_scope', models.CharField(choices=[('EVENT', 'Event'), ('TRACK', 'Track')], default='EVENT', max_length=20)),
                ('ranking_method', models.CharField(choices=[('RAW_WEIGHTED_V1', 'Raw Weighted V1'), ('RIDGE_JUDGE_OFFSET_V1', 'Ridge Judge Offset V1')], default='RAW_WEIGHTED_V1', max_length=30)),
                ('normalisation_lambda', models.FloatField(default=5.0)),
                ('show_public_progress', models.BooleanField(default=False)),
                ('active_publication_id', models.UUIDField(blank=True, null=True)),
                ('judging_frozen_at', models.DateTimeField(blank=True, null=True)),
                ('data_version', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'constraints': [models.CheckConstraint(condition=models.Q(('registration_opens_at__lt', models.F('registration_closes_at'))), name='check_event_reg_dates'), models.CheckConstraint(condition=models.Q(('submissions_opens_at__lt', models.F('submissions_closes_at'))), name='check_event_sub_dates'), models.CheckConstraint(condition=models.Q(('judging_opens_at__lt', models.F('judging_closes_at'))), name='check_event_judge_dates'), models.CheckConstraint(condition=models.Q(('min_team_size__gte', 1), ('min_team_size__lte', models.F('max_team_size'))), name='check_event_team_sizes'), models.CheckConstraint(condition=models.Q(('required_reviews__gte', 1)), name='check_event_required_reviews'), models.CheckConstraint(condition=models.Q(('normalisation_lambda__gt', 0)), name='check_event_norm_lambda_positive')],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=100)),
                ('description_md', models.TextField(blank=True, max_length=10000)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description_md', models.TextField(blank=True, max_length=10000)),
                ('amount_minor', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='events.track')),
            ],
            options={
                'db_table': 'prizes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('JUDGE', 'Judge'), ('ORGANISER', 'Organiser')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_memberships',
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user_membership')],
            },
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='unique_event_track_slug'),
        ),
    ]
