# Generated by Django 6.1.1 on 2026-09-29 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('allowed_parent_origins_json', models.JSONField(default=list)),
                ('theme', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark'), ('AUTO', 'Auto')], default='AUTO', max_length=10)),
                ('show_search', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.track')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embed_configuration', to='events.event')),
            ],
            options={
                'db_table': 'embed_configurations',
            },
        ),
    ]
