# Generated by Django 6.1.1 on 2026-09-28 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_eventinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('public_prefix', models.CharField(db_index=True, max_length=16)),
                ('secret_digest', models.CharField(max_length=64, unique=True)),
                ('scopes_json', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to='events.event')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_credentials',
                'indexes': [models.Index(fields=['event', 'owner_user', 'created_at'], name='idx_api_cred_owner')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_or_actor_key', models.CharField(max_length=128)),
                ('route_key', models.CharField(max_length=128)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_sha256', models.CharField(max_length=64)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='events.event')),
            ],
            options={
                'db_table': 'idempotency_records',
                'indexes': [models.Index(fields=['expires_at'], name='idx_idemp_expires')],
                'constraints': [models.UniqueConstraint(fields=('credential_or_actor_key', 'event', 'route_key', 'idempotency_key'), name='unique_idempotency_record')],
            },
        ),
    ]
