# Generated by Django 6.1.1 on 2026-09-28 16:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventinvitation'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=128)),
                ('schema_version', models.CharField(default='1.0', max_length=16)),
                ('entity_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to='events.event')),
            ],
            options={
                'db_table': 'domain_events',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('LEASED', 'Leased'), ('RETRY', 'Retry'), ('SUCCEEDED', 'Succeeded'), ('DEAD', 'Dead'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('lifetime_attempt_count', models.PositiveIntegerField(default=0)),
                ('replay_generation', models.PositiveIntegerField(default=0)),
                ('attempts_in_generation', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_owner', models.CharField(blank=True, max_length=128, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.IntegerField(blank=True, null=True)),
                ('last_error_class', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.domainevent')),
            ],
            options={
                'db_table': 'webhook_deliveries',
            },
        ),
        migrations.CreateModel(
            name='WebhookAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_headers_json', models.JSONField(default=dict)),
                ('response_body_redacted', models.TextField(blank=True, default='')),
                ('error_class', models.CharField(blank=True, max_length=64, null=True)),
                ('request_timestamp', models.DateTimeField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='integrations.webhookdelivery')),
            ],
            options={
                'db_table': 'webhook_attempts',
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2048)),
                ('allowed_event_types', models.JSONField(default=list)),
                ('secret_encrypted', models.CharField(max_length=512)),
                ('secret_key_version', models.CharField(default='v1', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhook_endpoints', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='events.event')),
            ],
            options={
                'db_table': 'webhook_endpoints',
            },
        ),
        migrations.AddField(
            model_name='webhookdelivery',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint'),
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('GENERATE_CERTIFICATES', 'Generate Certificates'), ('EXPORT_EVENT', 'Export Event'), ('VALIDATE_IMPORT', 'Validate Import'), ('APPLY_IMPORT', 'Apply Import')], max_length=64)),
                ('parameters_json', models.JSONField(default=dict)),
                ('input_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('lease_owner', models.CharField(blank=True, max_length=128, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(blank=True, null=True)),
                ('result_storage_key', models.CharField(blank=True, max_length=512, null=True)),
                ('result_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='events.event')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'background_jobs',
                'indexes': [models.Index(fields=['state', 'lease_until', 'created_at'], name='idx_bg_job_state_lease'), models.Index(fields=['event', 'requested_by', 'created_at'], name='idx_bg_job_event_req')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='chk_bg_job_attempts_nonneg'), models.CheckConstraint(condition=models.Q(('progress_current__gte', 0)), name='chk_bg_job_prog_nonneg')],
            },
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['event', 'created_at'], name='idx_domain_event_event_time'),
        ),
        migrations.AddIndex(
            model_name='domainevent',
            index=models.Index(fields=['type', 'created_at'], name='idx_domain_event_type_time'),
        ),
        migrations.AddIndex(
            model_name='webhookattempt',
            index=models.Index(fields=['delivery', 'started_at'], name='idx_wh_attempt_deliv_time'),
        ),
        migrations.AddConstraint(
            model_name='webhookattempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='unique_wh_attempt_deliv_num'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['event', 'status'], name='idx_wh_ep_event_status'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['state', 'next_attempt_at', 'lease_until'], name='idx_wh_deliv_state_next'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='idx_wh_deliv_ep_created'),
        ),
        migrations.AddConstraint(
            model_name='webhookdelivery',
            constraint=models.UniqueConstraint(fields=('domain_event', 'endpoint'), name='unique_wh_delivery_event_endpoint'),
        ),
    ]
