# Generated by Django 6.1.1 on 2026-09-28 04:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('QUARANTINED', 'Quarantined')], default='ACTIVE', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('BALANCED', 'Balanced'), ('FIXTURE_OBSERVED', 'Fixture Observed'), ('DEMO_SYNTHETIC', 'Demo Synthetic')], default='MANUAL', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
                ('judge_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.eventmembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='submissions.project')),
                ('project_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judge_assignments', to='submissions.projectrevision')),
            ],
            options={
                'db_table': 'judge_assignments',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=20)),
                ('comment', models.TextField(blank=True, max_length=10000)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='judging.judgeassignment')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('FROZEN', 'Frozen')], default='DRAFT', max_length=20)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='events.event')),
            ],
            options={
                'db_table': 'rubrics',
            },
        ),
        migrations.AddField(
            model_name='judgeassignment',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='judging.rubric'),
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('description_md', models.TextField(blank=True, max_length=5000)),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='judging.rubric')),
            ],
            options={
                'db_table': 'criteria',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JudgeTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_tracks', to='events.eventmembership')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_judges', to='events.track')),
            ],
            options={
                'db_table': 'judge_tracks',
                'constraints': [models.UniqueConstraint(fields=('membership', 'track'), name='unique_judge_track_expertise')],
            },
        ),
        migrations.CreateModel(
            name='JudgeTrackPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_permissions', to='events.eventmembership')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permitted_judges', to='events.track')),
            ],
            options={
                'db_table': 'judge_track_permissions',
                'constraints': [models.UniqueConstraint(fields=('membership', 'track'), name='unique_judge_track_permission')],
            },
        ),
        migrations.CreateModel(
            name='ReviewRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('scores_snapshot', models.JSONField()),
                ('comment_snapshot', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('USER', 'User'), ('FIXTURE_IMPORT', 'Fixture Import'), ('PORTABLE_IMPORT', 'Portable Import')], default='USER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='judging.review')),
            ],
            options={
                'db_table': 'review_revisions',
                'constraints': [models.UniqueConstraint(fields=('review', 'number'), name='unique_review_revision_number')],
            },
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.PositiveSmallIntegerField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='judging.criterion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.review')),
            ],
            options={
                'db_table': 'review_scores',
                'constraints': [models.UniqueConstraint(fields=('review', 'criterion'), name='unique_review_criterion_score'), models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 5)), name='check_review_score_range_1_to_5')],
            },
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(fields=('event', 'version_number'), name='unique_event_rubric_version'),
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['event', 'judge_membership', 'status'], name='idx_judge_work_queue'),
        ),
        migrations.AddIndex(
            model_name='judgeassignment',
            index=models.Index(fields=['event', 'project', 'status'], name='idx_org_coverage'),
        ),
        migrations.AddConstraint(
            model_name='judgeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('judge_membership', 'project'), name='unique_active_judge_assignment_per_project'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'key'), name='unique_rubric_criterion_key'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='check_criterion_weight_positive'),
        ),
    ]
